[package]
name = "rust-connect"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dotenv = "0.15.0"
dotenv-linter = "3.3.0"
dotenv-vault = "0.1.2"
ssh2 = "0.9.4"
